dist: xenial
language: python
arch:
    - amd64
python:
    - "3.7"
jobs:
    exclude:
      - arch: ppc64le
        python: pypy3.5-7.0.0
      - arch: ppc64le
        python: pypy3.6-7.1.1
install:
    - pip install '.[tests]'
script:
    # Only run mypy in "3.9" job, because installing it fails in PyPy jobs
    - |
      if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then
        pip install mypy &&
        mypy .
      fi
    - pytest --flake8 --cov=base58 --benchmark-disable .
after_success:
    coveralls
